CC = g++
MOC = moc
POD2MAN = pod2man

PREFIX ?= /usr/local
DESTDIR ?= $(PREFIX)/bin
MANDIR ?= $(PREFIX)/man/man1
DEFAULT_CODEC ?= DEFAULT

QT_CFLAGS = $(shell pkg-config QtCore QtGui --cflags)
QT_LIBS = $(shell pkg-config QtCore QtGui --libs)


ifeq '$(DEBUG)' 'yes'
  CXXFLAGS = -g
else
  CXXFLAGS += -DNDEBUG
endif
export $(DEBUG)

ifneq '$(DEFAULT_CODEC)' 'DEFAULT'
  CXXFLAGS += -DDEFAULT_CODEC=\"$(DEFAULT_CODEC)\"
endif
export $(DEFAULT_CODEC)

CXXFLAGS += -Wall -Wno-long-long -pedantic



